# Challenge: Promotions

In this challenge, you'll develop codes to parse and analyze data returned from another API on Zalando such as [Promos homme (Men's Promotions)
](https://www.zalando.fr/promo-homme/) or [Promos femme (Women's Promotions)](https://www.zalando.fr/promo-femme/). The workflow is almost the same as in the guided lesson but you'll work with different data.

## Obtaining the link

Wrote your codes in the cell below to obtain the data from the API endpoint you choose. A recap of the workflow:

1. Examine the webpages and choose one that you want to work with.

1. Use Google Chrome's DevTools to inspect the XHR network requests. Find out the API endpoint that serves data to the webpage.

1. Test the API endpoint in the browser to verify its data.

1. Change the page number offset of the API URL to test if it's working.

In [ ]:
url='https://www.zalando.fr/api/catalog/articles?categories=promo-femme&limit=84&offset=84&sort=popularity'

## Reading the data

In the next cell, use Python to obtain data from the API endpoint you chose in the previous step. Workflow:

1. Import libraries.

1. Define the initial API endpoint URL.

1. Make request to obtain data of the 1st page. Flatten the data and store it in an empty object variable.

1. Find out the total page count in the 1st page data.

1. Use a FOR loop to make requests for the additional pages from 2 to page count. Append the data of each additional page to the flatterned data object.

1. Print and review the data you obtained.

In [7]:
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize
import urllib

In [9]:
response = urllib.request.urlopen
results = json.load(response)

flattened_data = json_normalize(results)
flattened_data1 = json_normalize(flattened_data.articles[0])
flattened_data1.head()

/home/joyce/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  after removing the cwd from sys.path.
/home/joyce/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,sku,name,sizes,url_key,media,brand_name,is_premium,family_articles,flags,product_group,delivery_promises,price.original,price.promotional,price.has_different_prices,price.has_different_original_prices,price.has_different_promotional_prices,price.has_discount_on_selected_sizes_only,amount,price.base_price,outfits
0,M9121G0V8-K11,COFI6-N - Blazer - blau,"[36, 38, 40, 42, 46]",mango-cofi6-n-blazer-blue-m9121g0v8-k11,[{'path': 'spp-media-p1/d31b3e0aca303f21bff19f...,Mango,False,[],"[{'key': 'discountRate', 'value': '-25%', 'tra...",clothing,[],"39,99 €","29,99 €",False,False,False,False,NaN,NaN,NaN
1,AD115O045-A11,STAN SMITH - Baskets basses - ftwwht/ftwwht/cr...,"[36, 38, 40, 42, 44, 46, 48, 36 2/3, 37 1/3, 3...",adidas-originals-stan-smith-baskets-basses-foo...,[{'path': 'spp-media-p1/cce0afbed85e3ea2878af4...,adidas Originals,False,[],"[{'key': 'discountRate', 'value': 'Jusqu’à -10...",shoe,[],"94,95 €","85,45 €",True,False,True,False,NaN,NaN,NaN
2,TA111B16L-Q11,Escarpins à talons hauts - black,"[38, 39, 40, 41]",tamaris-slip-on-escarpins-ta111b16l-q11,[{'path': 'spp-media-p1/6f7b874ff4863e22a27a9f...,Tamaris,False,[],"[{'key': 'discountRate', 'value': '-10%', 'tra...",shoe,[],"49,95 €","44,95 €",False,False,False,False,NaN,NaN,NaN
3,NM321G03S-Q11,NMREBEL - Veste en similicuir - black,"[36, 38, 40, 42, 44]",noisy-may-nmrebel-veste-en-similicuir-black-nm...,[{'path': 'spp-media-p1/5ceb842321a03901a77bd7...,Noisy May,False,[],"[{'key': 'discountRate', 'value': '-15%', 'tra...",clothing,[],"39,99 €","33,99 €",False,False,False,False,NaN,NaN,NaN
4,TO111A06I-K11,LOVES BEACH - Tongs - blue,"[36, 37, 38, 39, 40, 41, 42]",tommy-hilfiger-loves-beach-tongs-blue-to111a06...,[{'path': 'spp-media-p1/98690adbe1b23c98ba60e0...,Tommy Hilfiger,False,[],"[{'key': 'discountRate', 'value': '-20%', 'tra...",shoe,[],"29,95 €","23,95 €",False,False,False,False,NaN,NaN,NaN

In [ ]:
flattened_data1.info(verbose=True)

In [ ]:
total_pages=results['pagination']['page_count']

df=pd.flattened_data1()
for i in range(total_pages):
    k=84*i
    url='https://www.zalando.fr/api/catalog/articles?categories=promo-femme&limit=84&offset=84&sort=popularity'
    response = requests.get(url)
    results = response.json()
    flattened_data = json_normalize(results)
    flattened_data1 = json_normalize(flattened_data.articles[0])
    flattened_data1=flattened_data1.set_index('sku')
    df = df.append(flattened_data1) #aca no se que hacer
df.head()

## Bonus

Extract the following information from the data:

* The trending brand.

* The product(s) with the highest discount.

* The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).

In [ ]:
#Trending brand
df.brand_name.value_counts().index[0]

In [ ]:
#The product(s) with the highest discount. Esto no lo entiendo!!!!!!
df['price.original']=df['price.original'].str.extract('(\d*,\d*)')
df['price.promotional']=df['price.promotional'].str.extract('(\d*,\d*)')#que esta ectrayendo?

df['price.original'] = [x.replace(',', '.') for x in df['price.original']]#una linea para remplazar , por . u hacer una columna mas?
df['price.promotional'] = [x.replace(',', '.') for x in df['price.promotional']]

df['discount_amount']=df['price.original'].astype(float)-df['price.promotional'].astype(float)
df1=df.copy()

In [ ]:
total_disc=df1.groupby(['brand_name']).sum().discount_amount

In [ ]:
total_disc.sort_values(ascending=False).index[0]